[cerebrium]
project_id = "p-d91d0d77"   # isi pakai punyamu

[cerebrium.deployment]
name = "auto-runner"
python_version = "3.12"
disable_auth = false
timeout = 14400   # 4 jam

[cerebrium.hardware]
region = "us-east-1"

cpu = 2
memory = 8

gpu_count = 1
compute = "AMPERE_A10"

[cerebrium.entrypoint]
file = "main.py"
function = "run"
