- name: Set Project
  run: |
    cerebrium project set $CEREBRIUM_PROJECT_ID \
    --service-account-token $CEREBRIUM_SERVICE_ACCOUNT_TOKEN \
    --verbose
  env:
    CEREBRIUM_PROJECT_ID: ${{ secrets.CEREBRIUM_PROJECT_ID }}
    CEREBRIUM_SERVICE_ACCOUNT_TOKEN: ${{ secrets.CEREBRIUM_SERVICE_ACCOUNT_TOKEN }}

- name: Deploy
  run: |
    cerebrium deploy \
    --service-account-token $CEREBRIUM_SERVICE_ACCOUNT_TOKEN \
    --verbose
  env:
    CEREBRIUM_SERVICE_ACCOUNT_TOKEN: ${{ secrets.CEREBRIUM_SERVICE_ACCOUNT_TOKEN }}
